# Generated by Django 4.2.19 on 2025-03-05 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('iata', models.CharField(max_length=3, unique=True)),
                ('tipo', models.CharField(max_length=20)),
                ('st', models.CharField(max_length=10)),
                ('prazo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_minima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coleta_desc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('entrega_desc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='cotacao.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='cotacao.cidade')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origens', to='cotacao.cidade')),
            ],
        ),
    ]
