# Generated by Django 4.2.19 on 2025-03-06 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('tipo', models.CharField(choices=[('DIRETO', 'Direto'), ('ST', 'Serviço Terceirizado')], max_length=20)),
                ('prazo_base', models.IntegerField(default=0)),
                ('prazo_adicional', models.IntegerField(default=0)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Iata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('standard', 'Standard'), ('e_facil', 'E-Fácil'), ('veloz', 'Veloz')], max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_ate_5kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tarifa_por_kg_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('prazo', models.IntegerField(default=0)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='cotacao.cidade')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='cotacao.servico')),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coleta_desc', models.CharField(max_length=255)),
                ('entrega_desc', models.CharField(max_length=255)),
                ('prazo', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_destino', to='cotacao.cidade')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_origem', to='cotacao.cidade')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='cotacao.servico')),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes_destino', to='cotacao.cidade')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes_origem', to='cotacao.cidade')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='cotacao.servico')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='iata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.iata'),
        ),
    ]
