# Generated by Django 4.2.19 on 2025-03-06 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origem_tarifa', to='cotacao.cidade'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='raio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.cidade'),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='prazo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.servico'),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='tarifa_ate_5kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='tarifa_por_kg_adicional',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
