# Generated by Django 4.2.19 on 2025-03-07 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0002_tarifa_origem_tarifa_raio_alter_tarifa_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaRaio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raio', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.cidade')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.servico')),
            ],
        ),
    ]
