# Generated by Django 4.2.19 on 2025-03-08 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0003_tarifaraio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_ate_5kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_por_kg_adicional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo', models.IntegerField()),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.cidade')),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origem_tarifa_standard', to='cotacao.cidade')),
            ],
        ),
        migrations.DeleteModel(
            name='Tarifa',
        ),
    ]
