# Generated by Django 4.2.19 on 2025-03-08 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0004_tarifastandard_delete_tarifa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifaraio',
            name='cidade',
        ),
        migrations.AddField(
            model_name='tarifaraio',
            name='iata',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cotacao.iata'),
        ),
        migrations.AddField(
            model_name='tarifastandard',
            name='servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cotacao.servico'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='iata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='cotacao.iata'),
        ),
        migrations.AlterField(
            model_name='tarifastandard',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_standard', to='cotacao.cidade'),
        ),
        migrations.AlterField(
            model_name='tarifastandard',
            name='origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origem_tarifa', to='cotacao.cidade'),
        ),
    ]
