# Generated by Django 4.2.19 on 2025-03-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0005_remove_tarifaraio_cidade_tarifaraio_iata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifaraio',
            name='iata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cotacao.iata'),
        ),
        migrations.AlterField(
            model_name='tarifastandard',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.servico'),
        ),
    ]
