# Generated by Django 4.2.19 on 2025-03-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0006_alter_tarifaraio_iata_alter_tarifastandard_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
