# Generated by Django 4.2.19 on 2025-03-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0008_tarifast'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='st_codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
