# Generated by Django 4.2.19 on 2025-03-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0009_cidade_st_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarifaraio',
            old_name='valor',
            new_name='valor_base',
        ),
        migrations.AddField(
            model_name='tarifaraio',
            name='valor_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
