# Generated by Django 4.2.19 on 2025-03-14 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0011_tarifaraio_valor_fixo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifastandard',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='tarifastandard',
            name='origem',
        ),
        migrations.AddField(
    model_name='tarifastandard',
    name='iata',
    field=models.ForeignKey(
        to='cotacao.iata',
        on_delete=models.CASCADE,
        related_name='tarifas_standard',
        null=True,  # Permitir valores nulos temporariamente para evitar erro
        blank=True
    ),
),

    ]
