# Generated by Django 4.2.19 on 2025-03-17 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0012_remove_tarifastandard_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
    model_name='tarifastandard',
    name='iata',
    field=models.ForeignKey(to='cotacao.iata', on_delete=models.CASCADE, related_name='tarifas_standard', null=True, blank=True),
),
    ]
